#
# Copyright 2016-present the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: '3'

services:
  register:
    image: registry.cn-beijing.aliyuncs.com/dc3/dc3-center-register:4.0.0-nacos
    restart: on-failure
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - JVM_XMS=512m
      - JVM_XMX=512m
      - JVM_XMN=256m
      - JVM_MS=128m
      - JVM_MMS=256m
    container_name: dc3-center-register
    hostname: dc3-center-register
    depends_on:
      - mysql
    volumes:
      - logs:/home/nacos/logs
    logging:
      driver: json-file
      options:
        max-size: '20m'
        max-file: '20'
    networks:
      dc3net:
        aliases:
          - dc3-center-register
  mysql:
    image: registry.cn-beijing.aliyuncs.com/dc3/dc3-mysql:2023.4.0.dev
    restart: on-failure
    ports:
      - '33306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=dc3
    container_name: dc3-mysql
    hostname: dc3-mysql
    volumes:
      - mysql:/var/lib/mysql
    logging:
      driver: json-file
      options:
        max-size: '20m'
        max-file: '20'
    networks:
      dc3net:
        aliases:
          - dc3-mysql

  mongo:
    image: registry.cn-beijing.aliyuncs.com/dc3/dc3-mongo:2023.4.0.dev
    restart: on-failure
    ports:
      - '37017:27017'
    container_name: dc3-mongo
    hostname: dc3-mongo
    volumes:
      - mongo_config:/data/configdb
      - mongo_db:/data/db
    logging:
      driver: json-file
      options:
        max-size: '20m'
        max-file: '20'
    networks:
      dc3net:
        aliases:
          - dc3-mongo

  redis:
    image: registry.cn-beijing.aliyuncs.com/dc3/dc3-redis:2023.4.0.dev
    restart: on-failure
    ports:
      - '36379:6379'
    container_name: dc3-redis
    hostname: dc3-redis
    volumes:
      - redis:/data
    logging:
      driver: json-file
      options:
        max-size: '20m'
        max-file: '20'
    networks:
      dc3net:
        aliases:
          - dc3-redis

  rabbitmq:
    image: registry.cn-beijing.aliyuncs.com/dc3/dc3-rabbitmq:2023.4.0.dev
    restart: on-failure
    ports:
      - '5672:5672'
      - '1883:1883'
      - '8883:8883'
      - '61613:61613'
      - '15672:15672'
    container_name: dc3-rabbitmq
    hostname: dc3-rabbitmq
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    logging:
      driver: json-file
      options:
        max-size: '20m'
        max-file: '20'
    networks:
      dc3net:
        aliases:
          - dc3-rabbitmq

  portainer:
    image: portainer/portainer:1.24.2
    command: -H unix:///var/run/docker.sock
    restart: on-failure
    ports:
      - '9000:9000'
    container_name: portainer
    hostname: dc3-portainer
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: json-file
      options:
        max-size: '20m'
        max-file: '20'
    networks:
      dc3net:
        aliases:
          - dc3-portainer

volumes:
  logs:
  mysql:
  mongo_config:
  mongo_db:
  redis:
  rabbitmq:
  portainer:

networks:
  dc3net:
    driver: bridge
...
