#
# Copyright 2016-present the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: '3'

services:
  web:
    image: registry.cn-beijing.aliyuncs.com/dc3/iot-dc3-web:2023.4.0.demo
    restart: always
    environment:
      - APP_API_PATH=dc3-gateway
      - APP_API_PORT=8000
    ports:
      - '8080:80'
    container_name: dc3-demo-web
    hostname: dc3-web
    depends_on:
      - gateway
    volumes:
      - demo_nginx:/var/log/nginx
    networks:
      dc3demonet:
        aliases:
          - dc3-web

  gateway:
    image: registry.cn-beijing.aliyuncs.com/dc3/dc3-gateway:2023.4.0.demo
    restart: always
    environment:
      - NODE_ENV=pro
    container_name: dc3-demo-gateway
    hostname: dc3-gateway
    depends_on:
      - register
      - auth
      - manager
      - data
    volumes:
      - demo_logs:/dc3-gateway/dc3/logs
    logging:
      driver: json-file
      options:
        max-size: '20m'
        max-file: '20'
    networks:
      dc3demonet:
        aliases:
          - dc3-gateway

  auth:
    image: registry.cn-beijing.aliyuncs.com/dc3/dc3-center-auth:2023.4.0.demo
    restart: always
    environment:
      - NODE_ENV=pro
    container_name: dc3-demo-center-auth
    hostname: dc3-center-auth
    depends_on:
      - register
      - rabbitmq
      - mysql
      - redis
      - mongo
    volumes:
      - demo_logs:/dc3-center/dc3-center-auth/dc3/logs
    logging:
      driver: json-file
      options:
        max-size: '20m'
        max-file: '20'
    networks:
      dc3demonet:
        aliases:
          - dc3-center-auth

  manager:
    image: registry.cn-beijing.aliyuncs.com/dc3/dc3-center-manager:2023.4.0.demo
    restart: always
    environment:
      - NODE_ENV=pro
    container_name: dc3-demo-center-manager
    hostname: dc3-center-manager
    depends_on:
      - register
      - rabbitmq
      - mysql
      - redis
      - mongo
    volumes:
      - demo_logs:/dc3-center/dc3-center-manager/dc3/logs
    logging:
      driver: json-file
      options:
        max-size: '20m'
        max-file: '20'
    networks:
      dc3demonet:
        aliases:
          - dc3-center-manager

  data:
    image: registry.cn-beijing.aliyuncs.com/dc3/dc3-center-data:2023.4.0.demo
    restart: always
    environment:
      - NODE_ENV=pro
    container_name: dc3-demo-center-data
    hostname: dc3-center-data
    depends_on:
      - register
      - rabbitmq
      - mysql
      - redis
      - mongo
    volumes:
      - demo_logs:/dc3-center/dc3-center-data/dc3/logs
    logging:
      driver: json-file
      options:
        max-size: '20m'
        max-file: '20'
    networks:
      dc3demonet:
        aliases:
          - dc3-center-data

  virtual:
    image: registry.cn-beijing.aliyuncs.com/dc3/dc3-driver-virtual:2023.4.0.demo
    restart: always
    environment:
      - NODE_ENV=pro
    container_name: dc3-demo-driver-virtual
    hostname: dc3-driver-virtual
    depends_on:
      - rabbitmq
      - manager
      - auth
      - data
    volumes:
      - demo_logs:/dc3-driver/dc3-driver-virtual/dc3/logs
    logging:
      driver: json-file
      options:
        max-size: '20m'
        max-file: '20'
    networks:
      dc3demonet:
        aliases:
          - dc3-driver-virtual

  register:
    image: registry.cn-beijing.aliyuncs.com/dc3/dc3-center-register:2023.4.0.demo
    restart: always
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - JVM_XMS=512m
      - JVM_XMX=512m
      - JVM_XMN=256m
      - JVM_MS=128m
      - JVM_MMS=256m
    container_name: dc3-demo-center-register
    hostname: dc3-center-register
    depends_on:
      - mysql
    volumes:
      - demo_logs:/dc3-center/dc3-center-register/dc3/logs
    logging:
      driver: json-file
      options:
        max-size: '20m'
        max-file: '20'
    networks:
      dc3demonet:
        aliases:
          - dc3-center-register

  mysql:
    image: registry.cn-beijing.aliyuncs.com/dc3/dc3-mysql:2023.4.0.demo
    restart: always
    container_name: dc3-demo-mysql
    hostname: dc3-mysql
    volumes:
      - demo_mysql:/var/lib/mysql
    logging:
      driver: json-file
      options:
        max-size: '20m'
        max-file: '20'
    networks:
      dc3demonet:
        aliases:
          - dc3-mysql

  mongo:
    image: registry.cn-beijing.aliyuncs.com/dc3/dc3-mongo:2023.4.0.demo
    restart: always
    container_name: dc3-demo-mongo
    hostname: dc3-mongo
    volumes:
      - demo_mongo_config:/data/configdb
      - demo_mongo_db:/data/db
    logging:
      driver: json-file
      options:
        max-size: '20m'
        max-file: '20'
    networks:
      dc3demonet:
        aliases:
          - dc3-mongo

  redis:
    image: registry.cn-beijing.aliyuncs.com/dc3/dc3-redis:2023.4.0.demo
    restart: always
    container_name: dc3-demo-redis
    hostname: dc3-redis
    volumes:
      - demo_redis:/data
    logging:
      driver: json-file
      options:
        max-size: '20m'
        max-file: '20'
    networks:
      dc3demonet:
        aliases:
          - dc3-redis

  rabbitmq:
    image: registry.cn-beijing.aliyuncs.com/dc3/dc3-rabbitmq:2023.4.0.demo
    restart: always
    container_name: dc3-demo-rabbitmq
    hostname: dc3-rabbitmq
    volumes:
      - demo_rabbitmq:/var/lib/rabbitmq
    logging:
      driver: json-file
      options:
        max-size: '20m'
        max-file: '20'
    networks:
      dc3demonet:
        aliases:
          - dc3-rabbitmq

volumes:
  demo_nginx:
  demo_logs:
  demo_mysql:
  demo_mongo_config:
  demo_mongo_db:
  demo_redis:
  demo_rabbitmq:

networks:
  dc3demonet:
    driver: 'bridge'
...